---
# TODO: refactor this into its own include
# and pass a variable for ctx
- name: Verify Requirements
  hosts: oo_all_hosts
  roles:
  - openshift_health_checker
  vars:
  - r_openshift_health_checker_playbook_context: install
  post_tasks:
  - action: openshift_health_check
    args:
      checks:
      - disk_availability
      - memory_availability
      - package_availability
      - package_version
      - docker_image_availability
      - docker_storage

- import-playbook: initialize_oo_option_facts.yml
  tags:
  - always

- name: Disable excluders
  hosts: oo_masters_to_config:oo_nodes_to_config
  tags:
  - always
  gather_facts: no
  roles:
  - role: openshift_excluder
    r_openshift_excluder_action: disable
    r_openshift_excluder_service_type: "{{ openshift.common.service_type }}"

- import-playbook: ../openshift-etcd/config.yml
  tags:
  - etcd

- import-playbook: ../openshift-nfs/config.yml
  tags:
  - nfs

- import-playbook: ../openshift-loadbalancer/config.yml
  tags:
  - loadbalancer

- import-playbook: ../openshift-master/config.yml
  tags:
  - master

- import-playbook: additional_config.yml
  tags:
  - master

- import-playbook: ../openshift-node/config.yml
  tags:
  - node

- import-playbook: ../openshift-glusterfs/config.yml
  tags:
  - glusterfs

- import-playbook: openshift_hosted.yml
  tags:
  - hosted

- import-playbook: service_catalog.yml
  when:
  - openshift_enable_service_catalog | default(false) | bool
  tags:
  - servicecatalog

- name: Re-enable excluder if it was previously enabled
  hosts: oo_masters_to_config:oo_nodes_to_config
  tags:
  - always
  gather_facts: no
  roles:
  - role: openshift_excluder
    r_openshift_excluder_action: enable
    r_openshift_excluder_service_type: "{{ openshift.common.service_type }}"
